### PR TITLE
fixed removal on EditJson not updating issue

### PR DESCRIPTION
**Pull request by lordstone**
This PR fixed the issue that in editJSON popup, any removal of elements won't update the data issue.

The issue was caused because the `saveJSON` function does not call `change` function, which update the data

### CODE REVIEW

**Review by Syzygy24 — APPROVED** [review]
👍

**Review by Syzygy24 — CHANGES_REQUESTED** [review]
bower_components folder is getting committed / merged in this pr.

**Comment by Syzygy24** [comment]
kk resolve merge conflict and then should be good to go.

**Comment by lordstone** [comment]
Finally

**Review by Syzygy24 — APPROVED** [review]

**Pull request merged**
