### PR TITLE
fix the bug of keep bouncing in between

### PR DESCRIPTION
**Pull request by lordstone**
This should fix it

### CODE REVIEW

**Review by Syzygy24 — CHANGES_REQUESTED** [review]
Let's bump the version up to 0.9.1

**Comment by lordstone** [comment]
👍

**Comment by lordstone** [comment]
hold on, i might need to separate _bower.css with some other name that 'save' it because datetime-picker is using it

**Comment by lordstone** [comment]
👍

**Review by Syzygy24 — APPROVED** [review]

**Pull request merged**
